import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/NavBar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "the nkini project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body
        className={`${inter.className} w-full bg-center bg-fixed bg-no-repeat bg-cover p-b-[300px]`}
      >
        <div className=" w-full h-full pb-96 text-black bg-cover">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
